### PR TITLE
Translate changelog for 1.2.3

### PR DESCRIPTION
**Pull request by 4sensegaming**
The latest versions of the translated docs didn't seem to make it into the patch, even though I did include them in my last pull request. Please, merge all po files in their current state from my branch into master in a future patch. Not urgent. The translation works, it's just cosmetic and stylistic changes that didn't seem to make it into the 1.2.3 update.

### CODE REVIEW

**Comment by Danstiv** [comment]
There are some strange things in the master branch, I’ll review it tomorrow and figure out what got lost and where.

**Comment by Danstiv** [comment]
Hello @4sensegaming,
Please merge master into your branch in the future before making any changes.
Now I don't know how to resolve these conflicts because I don't know Czech.
If you are sure that all your changes are correct, let me resolve the conflicts in favor of your branch, and you check everything again.

**Comment by 4sensegaming** [comment]
I'm really sorry about that! In my excuse, I'm only just getting started with Github and Git repositories and this is the first one I've ever collaborated on, so it's all still new to me. I'll make sure this doesn't happen in the future.
Yeah, I'm sure the changes are correct / more up-to-date / better on my end at the time. I've triple checked my current translation files against what's currently in the public game.

**Comment by 4sensegaming** [comment]
Actually, @Danstiv let me close this pull request and make a new one instead. I've made a couple more tweaks on my end in the meantime.

**Pull request closed without merging**
