### PR TITLE
translate to indonesian

### PR DESCRIPTION
**Pull request by MuhammadGagah**
Hi I have translated this game into Indonesian

### CODE REVIEW

**Comment by Danstiv** [comment]
Hello @MuhammadGagah!
First of all, thanks for your contribution!
I corrected something in your pr.
Po files must use two-letter names, and the added documentation directory must not contain files other than .po

After these corrections, the script detected untranslated strings, unfortunately, there was an error in our scripts, due to which some strings for translation were formed incorrectly.
Please wait while we fix it, after which I will give you further instructions.

**Comment by Danstiv** [comment]
So I corrected the scripts, and merged master into the branch with your translation.
Please pull new changes, update the translations of agsharp and ballbouncer from the new pot files, and translate the new strings.

**Comment by MuhammadGagah** [comment]
@Danstiv  I've finished fixing translations, do I have to create a new PR again? I don't know how to update a branch that is already in this pr.

**Comment by Danstiv** [comment]
This is another problem in our scripts, sorry for the inconvenience.

**Comment by Danstiv** [comment]
I force pushed your branch, so to continue the translation later do the following:
```
git reset 9c9af53
git pull
```
And thanks for your contribution! We will try to release an update with your translation in the coming weeks.

**Pull request merged**
